version: '3'
services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/todolist
    ports:
      - "8000:8000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx  # Dockerfile для Nginx
    ports:
      - "80:80"  # Прокидываем порт 80 для Nginx
    depends_on:
      - web  # Используем правильное имя сервиса, зависимость от Django
