# Dockerfile для Nginx

# Используем официальный образ Nginx
FROM nginx:latest

# Копируем конфигурационный файл Nginx в директорию conf.d
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Устанавливаем порт, на котором будет слушать Nginx
EXPOSE 80

# Команда для запуска Nginx
CMD ["nginx", "-g", "daemon off;"]
